name: Test and Release

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  bump_version:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: patch

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

  release:
      needs: bump_version
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == github.repository_owner
      permissions:
        contents: write
        id-token: write
        issues: write
        pull-requests: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build

        - name: Extract version from __init__.py
          id: get_version
          shell: python
          run: |
            import re
            version_file = 'src/getIP/__init__.py'
            with open(version_file, 'r') as file:
                content = file.read()
            version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]", content, re.M)
            if version_match:
                version = version_match.group(1)
                print(f"::set-output name=VERSION::{version}")
            else:
                raise RuntimeError("Unable to find version string.")

        - name: Build package
          run: python -m build

        - name: Publish package to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1

        - name: Create GitHub Release
          uses: actions/create-release@v1
          with:
            tag_name: ${{ steps.get_version.outputs.VERSION }}
            release_name: Release ${{ steps.get_version.outputs.VERSION }}
            body: |
              Changelog:
              - Description of changes in this release.
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}